name = "feline"
version = "0.1.0"
defaultTargets = ["feline"]

[[lean_lib]]
name = "Feline"

[[lean_exe]]
name = "feline"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"
